---
global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'email'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#yogsottot-webhook'
        send_resolved: true
  - name: 'email'
    email_configs:
      - to: 'admin@domain.tld'
        send_resolved: true
        from: 'alert@domain.tld'
        smarthost: 'smtp.yandex.ru:587'
        auth_username: 'alert@domain.tld'
        auth_password: 'SecRetPas$$word'

