FROM ruby:2.3-alpine
RUN apk --no-cache add make=4.2.1-r2 gcc=6.4.0-r9 libc-dev=0.7.1-r0

ENV APP_HOME /app
WORKDIR $APP_HOME

COPY Gemfile* $APP_HOME/
RUN bundle install
COPY . $APP_HOME

ENV COMMENT_DATABASE_HOST comment_db
ENV COMMENT_DATABASE comments

CMD ["puma"]
