---
# https://docs.docker.com/compose/compose-file/
version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
       aliases:
       - post_db
       - comment_db
  ui:
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${HOST_PORT}:${APP_PORT}/tcp
    networks:
      - front_net
  post:
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      back_net:
       aliases:
       - comment
      front_net:
       aliases:
       - comment
  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      back_net:
       aliases:
       - post
      front_net:
       aliases:
       - post

volumes:
  post_db:

networks:
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
  front_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
