---
# https://docs.docker.com/compose/compose-file/
version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${HOST_PORT}:${APP_PORT}/tcp
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 172.17.0.1:24224
        tag: service.ui
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - front_net
  post:
    image: ${USERNAME}/post:${POST_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 172.17.0.1:24224
        tag: service.post
    networks:
      back_net:
        aliases:
          - comment
      front_net:
        aliases:
          - comment
  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    depends_on:
      - post_db
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
      - COMMENT_DATABASE_HOST=comment_db
      - COMMENT_DATABASE=comments
    networks:
      back_net:
        aliases:
          - post
      front_net:
        aliases:
          - post

volumes:
  post_db:

networks:
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
  front_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
