---
# https://docs.docker.com/compose/compose-file/
version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
       aliases:
       - post_db
       - comment_db
  ui:
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${HOST_PORT}:${APP_PORT}/tcp
    networks:
      - front_net
  post:
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      back_net:
       aliases:
       - comment
      front_net:
       aliases:
       - comment
  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      back_net:
       aliases:
       - post
      front_net:
       aliases:
       - post
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - front_net
      - back_net
  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      back_net:
       aliases:
       - node-exporter
  mongodb_exporter:
    image: ${USERNAME}/mongodb_exporter:${MONGO_EXPORTER_VERSION}
    networks:
      back_net:
       aliases:
       - mongodb-exporter
  blackbox-exporter:
    #image: prom/blackbox-exporter:${BLACKBOX_EXPORTER_VERSION}
    image: ${USERNAME}/blackbox-exporter:${BLACKBOX_EXPORTER_VERSION}
    #command:
    #  - --config.file=/etc/blackbox_exporter/blackbox.yml
    #volumes:
    #  - /home/docker-user/blackbox_exporter:/etc/blackbox_exporter
    ports:
      - '9115:9115'
    networks:
      back_net:
       aliases:
       - blackbox-exporter
      front_net:
       aliases:
       - blackbox-exporter


volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
  front_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
