kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: aiRhMj7q413qv1DZvm5o+2bB9dVBAKUPhC7oBcIqtSA=
      - identity: {}
